alternative metal:
- funk metal
- nu metal
- rap metal
alternative rock:
- alt-country
- alternative dance
- alternative metal
- alternative pop
- britpop
- dream pop
- grunge
- indie rock
- shoegaze
avant-prog:
- zeuhl
black metal:
- ambient black metal
- atmospheric black metal
- avant-garde black metal
- black 'n' roll
- blackgaze
- depressive black metal
- experimental black metal
- industrial black metal
- melodic black metal
- pagan black metal
- post-black metal
- progressive black metal
- symphonic black metal
- technical black metal
classical:
- modern classical
country:
- alt-country
- americana
death metal:
- atmospheric death metal
- avant-garde death metal
- blackened death metal
- brutal death metal
- melodic death metal
- progressive death metal
- symphonic death metal
- technical death metal
doom metal:
- funeral doom metal
electronic:
- alternative dance
- ambient
- big beat
- breakcore
- bubblegum bass
- chillwave
- chiptune
- dance-punk
- disco
- downtempo
- drone
- drum and bass
- dubstep
- ebm
- electro
- electronica
- electropop
- eurodance
- folktronica
- footwork
- future garage
- glitch
- glitch hop
- glitch pop
- hardstyle
- house
- hyperpop
- idm
- indietronica
- industrial
- krautrock
- noise
- synthpop
- synthwave
- techno
- trance
- trip-hop
- vaporwave
- wonky
emo:
- emoviolence
- screamo
experimental rock:
- avant-prog
- brutal prog
- krautrock
- no wave
folk:
- basque folk
- canzone d'autore
- chamber folk
- indie folk
- neofolk
- psychedelic folk
folk metal:
- oriental metal
funk:
- afrobeat
hardcore punk:
- grindcore
- melodic hardcore
- metalcore
- post-hardcore
heavy metal:
- nwobhm
hip-hop:
- abstract hip-hop
- alternative hip-hop
- boom bap
- cloud rap
- conscious hip-hop
- east coast rap
- emo rap
- experimental hip-hop
- g-funk
- gangsta rap
- hardcore hip-hop
- jazz rap
- trap
- trip-hop
indie rock:
- indie folk
- indie pop
- lo-fi
- new rave
- slowcore
industrial:
- death industrial
- martial industrial
jazz:
- acid jazz
- avant-garde jazz
- bebop
- big band
- contemporary jazz
- cool jazz
- dark jazz
- experimental big band
- free jazz
- hard bop
- jazz fusion
- jazz-funk
- modal jazz
- nu jazz
- post-bop
- smooth jazz
- spiritual jazz
- swing
- vocal jazz
metal:
- alternative metal
- black metal
- cyber metal
- death metal
- doom metal
- drone metal
- folk metal
- glam metal
- gothic metal
- groove metal
- heavy metal
- industrial metal
- metalcore
- pagan metal
- post-metal
- power metal
- progressive metal
- sludge metal
- speed metal
- stoner metal
- symphonic metal
- thrash metal
- viking metal
metalcore:
- deathcore
- mathcore
- melodic metalcore
- progressive metalcore
modern classical:
- minimalism
noise:
- harsh noise
- power electronics
- power noise
pop:
- ambient pop
- anime
- art pop
- baroque pop
- bedroom pop
- chamber pop
- city pop
- denpa
- easy listening
- electropop
- indie pop
- pop rock
- shibuya-kei
- synthpop
- teen pop
pop rock:
- power pop
- soft rock
post-punk:
- coldwave
- gothic rock
progressive metal:
- avant-garde metal
- djent
- jazz metal
- math metal
- progressive black metal
- progressive death metal
- progressive deathcore
- progressive metalcore
- progressive power metal
- progressive thrash metal
progressive rock:
- andalusian rock
- avant-prog
- brutal prog
- canterbury scene
- crossover prog
- eclectic prog
- heavy prog
- jazz rock
- krautrock
- neo-prog
- progressive folk
- proto-prog
- symphonic prog
- zeuhl
- zolo
psychedelic folk:
- freak folk
psychedelic rock:
- acid rock
- heavy psych
- neo-psychedelia
- psychedelic folk
- psychedelic soul
- raga rock
- space rock
punk rock:
- art punk
- dance-punk
- emo
- garage punk
- hardcore punk
- pop punk
- post-punk
- proto-punk
- ska punk
- skate punk
- synth punk
r&b:
- boogie
- doo-wop
- funk
- soul
rock:
- alternative rock
- aor
- art rock
- blues rock
- country rock
- experimental rock
- folk rock
- garage rock
- glam rock
- hard rock
- jam band
- math rock
- metal
- new wave
- noise rock
- pop rock
- post-rock
- progressive rock
- psychedelic rock
- punk rock
- rock and roll
- southern rock
- stoner rock
- surf rock
rock and roll:
- rockabilly
sludge metal:
- atmospheric sludge metal
soundtracks:
- film score
- video game music
techno:
- dub techno
- minimal techno
trance:
- psytrance
