abstract hip-hop:
- abstract hip hop
afrobeat:
- afrobeats
alt-country:
- alternative country
alternative hip-hop:
- alternative hip hop
- alternative rap
alternative pop:
- alt pop
alternative rock:
- alternative
- modern alternative rock
andalusian rock:
- rock andaluz
art rock:
- art-rock
atmospheric sludge metal:
- atmospheric sludge
avant-garde jazz:
- avant-jazz
avant-prog:
- rio
- rock in opposition
black metal:
- orthodox black metal
canterbury scene:
- canterbury
chanson:
- chanson francaise
conscious hip-hop:
- conscious hip hop
death metal:
- old school death metal
depressive black metal:
- suicidal black metal
drone metal:
- drone doom metal
experimental hip-hop:
- experimental hip hop
experimental rock:
- avant rock
- avant-rock
film soundtracks:
- film music
- film score
free jazz:
- modern free jazz
funeral doom metal:
- funeral doom
hardcore punk:
- hardcore
hip-hop:
- hip hop
- hiphop
- rap
indie rock:
- indie
indietronica:
- indie electronic
jazz fusion:
- fusion
- jazz-rock fusion
- progressive fusion
- progressive jazz fusion
jazz rock:
- jazz-rock
lo-fi:
- lo-fi indie
metal:
- j-metal
modern classical:
- contemporary classical
neo-prog:
- neo prog
- neo progressive
- neo progressive rock
- neo-progressive
- neo-progressive rock
- neo-trad prog
neo-psychedelia:
- neo-psychedelic
nu metal:
- nu-metal
post-rock:
- post rock
- postrock
progressive folk:
- prog folk
progressive metal:
- prog metal
- prog-metal
progressive rock:
- instrumental progressive rock
- modern prog
- modern progressive rock
- new prog
- prog rock
- prog-rock
- prog-rokk
- progressive rock italiano
- progrock
- rock prog
- rock progressif francais
- rock progressivo italiano
- y2k prog
proto-prog:
- proto prog
- proto progressive
- proto-progressive
psychedelic rock:
- psychedelia
- psychedelic
psytrance:
- psychedelic trance
punk rock:
- j-punk
- punk
r&b:
- rhythm & blues
- rhythm and blues
- rnb
rock:
- j-rock
- jrock
rock and roll:
- rock & roll
- rock n roll
sludge metal:
- sludge
soundtracks:
- ost
- soundtrack
symphonic prog:
- symphonic progressive
- symphonic progressive rock
- symphonic rock
synthpop:
- synth pop
technical death metal:
- technical brutal death metal
thrash metal:
- old school thrash
trip-hop:
- trip hop
underground hip-hop:
- underground hip hop
- underground rap
video game music:
- game soundtrack
- video game
